#define MAXTHREADS 128
#define MAXBLOCKS 64

void globalparamsserial(	float*,
							float*,
							int*,
							int*,
							float*,
							float*,
							int*,
							int*,
							float*,
							float*,
							int*,
							int*,
							float*,
							float*,
							int*,
							int*,
							int*,
							int,
							int);

void globalparamsparallel(	float*,
							float*,
							int*,
							int*,
							float*,
							float*,
							int*,
							int*,
							float*,
							float*,
							int*,
							int*,
							float*,
							float*,
							int*,
							int*,
							int*,
							unsigned int,
							unsigned int,
							int,
							int);
