void reductionstep(         int*,
							float* ,
							float*,
							float* ,
							float* ,
							int* ,
							int* ,
							float* ,
							float* ,
							int* ,
							int* ,
							float* ,
							float* ,
							int* ,
							int* ,
							float* ,
							float* ,
							int* ,
							int* ,
							int* ,
							int* ,
							int* ,
							int ,
							int ,
							int ,
							int ,
							int ,
							float*);
