void trainclassifier (			float* ,
								int* ,
								int* ,
								float*,
								int ,
								int ,
								int ,
								float* ,
								float* ,
								float,
								int,
								float,
								float,
								float,
								float);
